{{- $vaultToken := index .Values "vault" "hashicorp" "token" -}}
{{- $vaultUrl := tpl (index .Values  "vault" "hashicorp" "url") . -}}
{{- $fullName := .Values.fullnameOverride -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-vault-setup
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: busybox
          imagePullPolicy: "IfNotPresent"
          command:
            - "/bin/sh"
            - "-c"
            - |
              sleep 10

              wget --header 'Content-Type: application/json' --header 'X-Vault-Token: {{ $vaultToken }}' \
              --post-file=/opt/config/cons_priv.json "{{ $vaultUrl }}/v1/secret/data/cons_priv"

              wget --header 'Content-Type: application/json' --header 'X-Vault-Token: {{ $vaultToken }}' \
              --post-file=/opt/config/cons_pub.json "{{ $vaultUrl }}/v1/secret/data/cons_pub"

              wget --header 'Content-Type: application/json' --header 'X-Vault-Token: {{ $vaultToken }}' \
              --post-file=/opt/config/prov_priv.json "{{ $vaultUrl }}/v1/secret/data/prov_priv"

              wget --header 'Content-Type: application/json' --header 'X-Vault-Token: {{ $vaultToken }}' \
              --post-file=/opt/config/prov_pub.json "{{ $vaultUrl }}/v1/secret/data/prov_pub"
          volumeMounts:
            - name: config-volume
              mountPath: /opt/config
      volumes:
        - name: config-volume
          configMap:
            name: {{ $fullName }}-vault-configmap
            defaultMode: 0777
